### PR TITLE
Add DotNet auto-build and Release on branch updates. + Configuration updates.

### PR DESCRIPTION
**Pull request by ly-nld**

### CODE REVIEW

**Comment by ks233** [comment]
感谢PR！其实现在发布的两个release里的`dist`文件夹是我从[另一个vue项目](https://github.com/ks233/ja-learner-webview/settings)生成然后手动复制过去的，这个仓库里没有那部分代码，所以自动生成发布可能有点问题。不知道有没有方法可以同时生成这边的c#程序和那边的vue页面，然后合并到一起发布？需不需要把那个仓库的东西搬过来？

另外这个规则似乎是每次main branch更新都自动生成一个release，如果只是更新一下readme它也自动生成一个release会不会太频繁了？可以改成手动控制吗？

没怎么做过开源项目，这方面了解的不多，麻烦大佬了。

**Comment by shaka0919** [comment]
> 感谢PR！其实现在发布的两个release里的`dist`文件夹是我从[另一个vue项目](https://github.com/ks233/ja-learner-webview)生成然后手动复制过去的，这个仓库里没有那部分代码，所以自动生成发布可能有点问题。不知道有没有方法可以同时生成这边的c#程序和那边的vue页面，然后合并到一起发布？需不需要把那个仓库的东西搬过来？
> 
> 另外这个规则似乎是每次main branch更新都自动生成一个release，如果只是更新一下readme它也自动生成一个release会不会太频繁了？可以改成手动控制吗？
> 
> 没怎么做过开源项目，这方面了解的不多，麻烦大佬了。

你可以尝试所有PR和修改在dev或者其他什么分支，累积一部分之后merge到main触发一次release。不过我也没怎么搞过auto build，只是个建议

**Comment by yihong0618** [comment]
> 感谢PR！其实现在发布的两个release里的`dist`文件夹是我从[另一个vue项目](https://github.com/ks233/ja-learner-webview)生成然后手动复制过去的，这个仓库里没有那部分代码，所以自动生成发布可能有点问题。不知道有没有方法可以同时生成这边的c#程序和那边的vue页面，然后合并到一起发布？需不需要把那个仓库的东西搬过来？
> 
> 另外这个规则似乎是每次main branch更新都自动生成一个release，如果只是更新一下readme它也自动生成一个release会不会太频繁了？可以改成手动控制吗？
> 
> 没怎么做过开源项目，这方面了解的不多，麻烦大佬了。

可以把 vue 那个项目做成 submoudle

**Comment by ly-nld** [comment]
afbeelding
I've tried to get it to work properly for the last few hours and this is the closest I've gotten. It automatically clones the `Vue` repository and builds it and puts it in the same place as the final ZIP. Sadly, I cannot figure out how to make it compile the DLL to Chinese Encoding. 

If anyone knows how to fix that, the auto-build is complete.

**Comment by yihong0618** [comment]
I have no win env for now, maybe help you do something later

**Comment by shaka0919** [comment]
is that possible to test the github action in a local environment?

**Comment by ly-nld** [comment]
> is that possible to test the github action in a local environment?

Unfortunately there aren’t many solutions on running GitHub Actions locally. I personally had a lot of trail and error on a seperate forked repository. Closest thing I can find is https://github.com/nektos/act

**Comment by ks233** [comment]
I found that only the `MainForm.cs` is somehow encoded in gb2312. The strings displayed weirdly are all in that file. I’ve converted it to utf8bom, and I think it will now be built correctly.

**Comment by ly-nld** [comment]
> I found that only the `MainForm.cs` is somehow encoded in gb2312. The strings displayed weirdly are all in that file. I’ve converted it to utf8bom, and I think it will now be built correctly.

I'll give it a try, I'll send an update soon

**Comment by ly-nld** [comment]
It seems to have worked! https://github.com/ly-nld/ja-learner/releases/tag/release-2023%E5%B9%B412%E6%9C%8829%E6%97%A5193505
afbeelding

**Comment by ly-nld** [comment]
I recommend you clone this ( https://github.com/ly-nld/ja-learner-static-files ) repository for static files and change that in the `.yml` file here: https://github.com/ly-nld/ja-learner/blob/786963d6ecf152e21071d7fdc2835965b04bb9ec/.github/workflows/dotnet_build.yml#L49

**Pull request merged**
